
[functions.create_staff_user]
enabled = true
verify_jwt = true
import_map = "./functions/create_staff_user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create_staff_user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create_staff_user/*.html" ]

[functions.upload_product_image]
enabled = true
verify_jwt = true
import_map = "./functions/upload_product_image/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/upload_product_image/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/upload_product_image/*.html" ]

[functions.delete_staff_user]
enabled = true
verify_jwt = true
entrypoint = "./functions/delete_staff_user/index.ts"

[functions.set_staff_password]
enabled = true
verify_jwt = true
import_map = "./functions/set_staff_password/deno.json"
entrypoint = "./functions/set_staff_password/index.ts"

[functions.verify_password]
enabled = true
verify_jwt = false
import_map = "./functions/verify_password/deno.json"
entrypoint = "./functions/verify_password/index.ts"
